//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANDTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int BannerId { get; set; }
        public Nullable<int> BannerGroupId { get; set; }
        public string HinhAnh { get; set; }
        public string Link { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public string TieuDe { get; set; }
        public Nullable<bool> HienThi { get; set; }
    
        public virtual BannerGroup BannerGroup { get; set; }
    }
}
