//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANDTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangSanXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangSanXuat()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int Id { get; set; }
        public string TenHang { get; set; }
        public string TruSoChinh { get; set; }
        public string QuocGia { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<bool> HienThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
        public string GetUrl()
        {
            var id = (int?)this.Id;
            if (!id.HasValue)
            {
                return string.Format("{0}", this.TuKhoa);
            }
            return string.Format("/{0}/{1}", "san-pham", this.TuKhoa);
        }
    }
}
