//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANDTDD.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.ThongSoKiThuat = new HashSet<ThongSoKiThuat>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> LoaiSP { get; set; }
        public Nullable<int> HangSX { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> GiaGoc { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public string MoTa { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public string HinhAnh { get; set; }
        public string AnhKhac { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsHot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoKiThuat> ThongSoKiThuat { get; set; }
        public string GetUrl()
        {
            if (!this.LoaiSP.HasValue)
            {
                return string.Format("/{0}", this.TuKhoa);
            }
            return string.Format("{0}/{1}/{2}", this.LoaiSanPham.GetUrl(), this.MaSP, this.TuKhoa);
        }
        public List<ImagesModel> GetImagesCollection()
        {
            List<ImagesModel> list = new List<ImagesModel>();
            if (string.IsNullOrEmpty(this.AnhKhac))
            {
                return list;
            }
            List<ImagesModel> list2 = new List<ImagesModel>();
            string[] strArray = this.AnhKhac.Split(new char[] { ';' });
            foreach (string str in strArray)
            {
                ImagesModel item = new ImagesModel();
                string[] strArray2 = str.Split(new char[] { ',' });
                item.FileName = strArray2[0].ToString();
                item.position = int.Parse(strArray2[1]);
                list2.Add(item);
            }
            return (from d in list2
                    orderby d.position
                    select d).ToList<ImagesModel>();
        }
    }
}
