//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANDTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int Id { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDungTT { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public string TieuDe { get; set; }
        public Nullable<bool> HienThi { get; set; }
    
        public virtual NhomTinTuc NhomTinTuc { get; set; }
        public string GetUrl()
        {
            if (!this.MaNhom.HasValue)
            {
                return string.Format("/{0}", this.TuKhoa);
            }
            return string.Format("{0}/{1}/{2}", this.NhomTinTuc.GetUrl(), this.Id, this.TuKhoa);
        }
    }
}
