//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBANDTDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraLoi
    {
        public int Id { get; set; }
        public System.DateTime NgayTraLoi { get; set; }
        public string NoiDungTL { get; set; }
        public Nullable<int> MaCauHoi { get; set; }
        public Nullable<bool> HienThi { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
    }
}
